source 'https://rubygems.org'

gem 'rails', '3.2.11'
gem 'mongo'
gem 'bootstrap-sass', '~> 3.3.4'
gem 'omniauth-openid'
gem 'omniauth-facebook'
gem 'omniauth-github'
#gem 'google-code-prettify-rails', '1.1.0'
gem 'aws-sdk'
gem 'annotate'
gem 'railties', '3.2.11'
# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'httparty'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.6'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'handlebars_assets'
  gem 'hamlbars', '~> 2.1.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'sqlite3'
  gem 'rspec-rails', '2.11.0'
  gem 'guard-rspec', '1.2.1'
  gem 'guard-spork', '1.2.0'
  gem 'spork', '0.9.2'
end

gem 'jquery-rails', '~> 3.1.2'

group :test do
  gem 'sqlite3'
  gem 'capybara', '1.1.2'
  gem 'factory_girl_rails', '4.1.0'
  gem 'cucumber-rails', '1.2.1', :require => false
  gem 'database_cleaner', '0.7.0'
  gem 'rb-fsevent', '0.9.1', :require => false
  gem 'growl', '1.0.3'
end

group :production do
  gem 'pg'
  gem 'thin'
  gem 'rack-google_analytics', :require => "rack/google_analytics"
end

gem 'delayed_job_mongoid'
gem 'rubyzip'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use thin as the app server
#gem 'thin'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
