FROM elasticsearch:1.7.1
MAINTAINER Maluuba Infrastructure Team <infrastructure@maluuba.com>

# Required for apt-add-repository
RUN apt-get -qq update
RUN apt-get -qq upgrade

RUN apt-get install wget
RUN apt-get -qq install bash

